Student_Management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('',views.Index.as_view()),
    path('college/<int:pk>',views.CollegeDetail.as_view(),name = 'college'),
    path('college/' , views.CollegeList.as_view()),
    path('college_create/' , views.CollegeCreate.as_view()),
    path('update_college/<int:pk>' , views.UpdateCollege.as_view()),
    path('student_create/' , views.StudentCreate.as_view()),
    path('student_list/' , views.StudentList.as_view()),
    path('student_delete/<int:pk>' , views.StudentDelete.as_view())
]

main/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length = 256)
    roll_no = models.IntegerField()
    college = models.ForeignKey('College' , on_delete = models.CASCADE)
    
    def __str__(self):
        return self.name

class College(models.Model):
    name = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)

from main import models
# Create your views here.

class Index(View):
    def get(self,request):
        return HttpResponse("GET request")

    def post(self,request):
        return HttpResponse("POST request")


'''
Django provides us with 5 generic views:
1) Detail View
2)List View
3)Create View
4)Update View
5)Delete View
'''

class CollegeDetail(DetailView):
    model = models.College
    template_name = 'college_detail.html'
    fields = '__all__'

class CollegeList(ListView):
    model = models.College
    template_name = 'college_list.html'
    fields = '__all__'
    context_object_name = 'colleges'  

class CollegeCreate(CreateView):
    model = models.College
    template_name = 'college_create.html'
    fields = "__all__"
    success_url = '/college'

class StudentCreate(CreateView):
    model = models.Student
    template_name = 'student_create.html'
    fields = '__all__'
    success_url = '/college'

class UpdateCollege(UpdateView):
    model = models.College
    template_name = 'college_create.html'
    fields = '__all__'
    success_url = '/college'

class StudentList(ListView):
    model = models.Student
    model2 = models.College
    template_name = 'student_list.html'
    fields = '__all__'
    context_object_name = 'students'

class StudentDelete(DeleteView):
    model = models.Student
    template_name = 'student_delete.html'
    success_url = '/student_list'

templates/college_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h>Create a College:</h>

    <form action="" method="POST">
        {% csrf_token %}

        {{ form }}

        <button type="submit">Submit</button>
        <button type="reset">Reset</button>
    </form>
</body>
</html>

templates/college_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>College</h1>

    Name : {{object.name}}

    <p>
        Students :
        <ul>
            {% for student in object.student_set.all %}
    
            <li>{{ student.name }}
            </li>
            {% endfor %}
        </ul>

    </p>
</body>
</html>

templates/college_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Colleges(List View)</h1>
    <li>
        {% for college in colleges %}
        <ul>
            <a href="{% url 'college' college.pk %}">{{college.name}}</a>
        </ul>
    </li>
        {% endfor %}
</body>
</html>

templates/student_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Add a Student:</h1>
    <form action="" method="POST">
        {% csrf_token %}

        {{ form }}

        <button type="submit">Submit</button>
        <button type="reset">Reset</button>

    </form>
</body>
</html>

templates/student_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Are you sure you want to delete?</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <button>No</button>
        <button type="submit">Yes</button>
    </form>
</body>
</html>

templates/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <h1>List of all students in all colleges:</h1>

        {% for student in students %}
            <ul>
                {{ student.name }}
                {{ student.roll_no }}
            </ul>
        {% endfor %}
</body>
</html>